<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>tpl</string>
		<string>html.tpl</string>
	</array>
	<key>foldingStartMarker</key>
	<string>(?x)
		(&lt;(?i:head|body|table|thead|tbody|tfoot|tr|div|select|fieldset|style|script|ul|ol|form|dl)\b.*?&gt;
		|&lt;!--(?!.*--&gt;)
		|\{\s*($|\?&gt;\s*$|//|/\*(.*\*/\s*$|(?!.*?\*/)))
		)</string>
	<key>foldingStopMarker</key>
	<string>(?x)
		(&lt;/(?i:head|body|table|thead|tbody|tfoot|tr|div|select|fieldset|style|script|ul|ol|form|dl)&gt;
		|^\s*--&gt;
		|(^|\s)\}
		)</string>
	<key>keyEquivalent</key>
	<string>^~H</string>
	<key>name</key>
	<string>HTML (Bottle)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.section.embedded.python</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.flow.python</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(%)\s*(end)\b</string>
			<key>name</key>
			<string>source.python.bottle.embedded.html</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*(%)</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>support.section.embedded.python</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>source.python.bottle.embedded.html</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.python.bottle</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>{{</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>support.section.embedded.python</string>
				</dict>
			</dict>
			<key>end</key>
			<string>}}</string>
			<key>name</key>
			<string>source.python.bottle.embedded.html</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.python.bottle</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>text.html.basic</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.html.python.bottle</string>
	<key>uuid</key>
	<string>A3BD6552-A757-4663-BEDD-3A21A1B3509D</string>
</dict>
</plist>
